### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by RajatSahani** [RajatSahani/markdown-portfolio#2]
- [x] @githubteacher 
- [ ] @crichID 
- [ ] @RajatSahani

**Comment by RajatSahani** [comment]
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
